### ISSUE TITLE
Add GUI component and tag features for Grab

### ISSUE THREAD

**Issue by ddx-510** [AY2122S2-CS2103T-W12-2/tp#100]
Currently, grab can only return results in the command window, we can improve by creating a new GUI that is selectable.
Grab can be extended to grab tele/ t/ such that we can grab by tags.

- [x] GUI
- [x] tag

**Comment by ddx-510** [comment]
GUI component has not been implemented

**Comment by pnutzz-0207** [comment]
typo in `resultDisplay`: "grab **succesfully**"
