### ISSUE TITLE
Test cases fail in AddTagCommandTest, DeleteTagCommandTest, EditCommandTest, ListTagCommandTest

### ISSUE THREAD

**Issue by 9teMare** [AY2122S2-CS2103T-W12-2/tp#84]
[PR#83](https://github.com/AY2122S2-CS2103T-W12-2/tp/pull/83)
In these test classes `AddTagCommandTest`, `DeleteTagCommandTest`, `EditCommandTest`, `ListTagCommandTest`, in total about 7 test cases are failing after I added support for `GeneralDisplay`.

`GeneralDisplay` is the panel on the right-hand side of the interface, next to the `PersonListPanel`. It was originally the `Profile` section, now, `GeneralDisplay` contains **a** `Profile` or **a** `TagList` at any given time, they will not co-exit. `GeneralDisplay` will show `Profile` when the user inputs command `profile $index`, and show `TagList` when the user inputs command `list_tag`, notice the latter directly affects `ListTagCommand` which causes tests in `ListTagCommandTest` to fail. 

Since the other 3 commands that are failing tests, namely `AddTagCommand`, `DeleteTagCommand` and `EditCommand` will change a particular `Person` object, corresponding UI implementations are added into the 3 commands respectively in order to "refresh" the `Profile` if the `Profile` is being displayed for the particular `Person`. Otherwise, the user will have to click on the `Person` being changed in `PersonListPanel`, or to call `profile $index` again to "refresh".

I think the issue is within the tests themselves due to missing stubs. Please take a look, thanks.

**Comment by ddx-510** [comment]
Currently, we are facing a big issue -> we are using the UI component within the command (logic component)
This is not a recommended way to handle because logic component in this project is supposed to handle data, and UI should respond to the data change.
Thus, we should avoid using UI component like MainWindow setup UI within command.
